name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Build
        run: |
          pnpm codegen

      - name: Check source state
        run: pnpm check-source-state

      - name: Types
        run: |
          pnpm check
          pnpm dtslint

      - name: Lint
        run: |
          pnpm circular
          pnpm lint

      - name: Test
        run: pnpm test
