name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm codegen
          pnpm codemod

      - name: Check source state
        run: git add packages/*/src && git diff-index --cached HEAD --exit-code packages/*/src

      - name: Types
        run: pnpm check

      - name: Lint
        run: |
          pnpm circular
          pnpm lint

      - name: Test
        run: pnpm test
